<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<style>
  body { font-family: DejaVu Sans, sans-serif;}

  #schema_I{width:80%;height: 100px !important;margin: 77px auto 0;position:relative;}

.i_wall_left_obj{position:absolute;width:10px;border-right: 2px solid #0078bf;height:100px;left:-10px;top:0;}
.i_wall_right_obj{position:absolute;width:10px;border-left: 2px solid #0078bf;height:100px;right:-10px;top:0;}
.i_wall_top_obj{position:absolute;width:100%;border-bottom: 2px solid #0078bf;height:10px;top:-10px;left:0;}
.i_wall_bottom_obj{position:absolute;width:100%;border-top: 2px solid #0078bf;height:10px;top:100px;left:0;}



.i_corner_1_obj_on{position:absolute;width:30px;height:28px;top:-4px;left:-4px;background-color:#fff;overflow: hidden;}
.i_corner_1_obj_on .pdf{position:absolute;top:4px;left:4px;width:40px;height:34px;border-left: 2px solid #0078bf;border-top: 2px solid #0078bf;border-radius: 10px; }
.i_corner_2_obj_on{position:absolute;width:30px;height:28px;top:-4px;right:-4px;background-color:#fff;overflow: hidden;}
.i_corner_2_obj_on .pdf{position:absolute;top:4px;left:-16px;width:40px;height:34px;border-right: 2px solid #0078bf;border-top: 2px solid #0078bf;border-radius: 10px;}
.i_corner_3_obj_on{position:absolute;width:30px;height:28px;top:76px;right:-4px;background-color:#fff;overflow: hidden;}
.i_corner_3_obj_on .pdf{position:absolute;top:-10px;left:-16px;width:40px;height:34px;border-right: 2px solid #0078bf;border-bottom: 2px solid #0078bf;border-radius: 10px;}
.i_corner_4_obj_on{position:absolute;width:30px;height:28px;top:76px;left:-4px;background-color:#fff;overflow: hidden;}
.i_corner_4_obj_on .pdf{position:absolute;top:-10px;left:4px;width:40px;height:34px;border-left: 2px solid #0078bf;border-bottom: 2px solid #0078bf;border-radius: 10px;}



.length{position:absolute;width:30px;height:20px;padding:4px;background:none;border: none;}

.length input{border:none;background:none;color:#666;width:100%;height:100%;font-size: 0.7em}
.i_length_1{left:-40px;top:30px;}
.i_length_2{top:-25px;left:50%;}
.i_length_3{right:-140px;top:50px;}
.i_length_4{bottom:-59px;left:50%;}


.corner{width:60px;height:58px;cursor:pointer;}
.corner_on{background-position:0 -145px !important;}
.corner_hover{background-position:0 -245px !important;}
.corner_on_hover{background-position:0 -45px !important;}

.wall{background: #fff;cursor: pointer;border: 2px solid #aaa;border-radius: 4px;height: 26px;width: 26px;}
.wall_hover{border: 2px solid red;}
.wall::before{content: "C";font-weight:bold;color:#ddd;text-align: center;width:100%;height:100%;font-size: 1.7em;line-height: 1.1em;margin: 0 auto;position: absolute;}
.wall_on{border: 2px solid #0078bf;}
.wall_on::before{color:#000;}

.sink{border:2px dashed #acacac;border-radius: 20px;font-size:0.9em;color:#acacac;cursor:pointer;text-align: center;display:none;}
.stove{border:2px dashed #acacac;font-size:0.9em;color:#acacac;cursor:pointer;text-align: center;display:none;}


.sink_on{border:2px solid #0078bf;color:#0078bf;display:block;}
.stove_on{border:2px solid #0078bf;color:#0078bf;display:block;}

.i_wall_left{position:absolute;left:-10px;top:50%;margin-top:-10px;}
.i_wall_top{position:absolute;left:50%;top:-10px;margin-left:-10px;}
.i_wall_right{position:absolute;right:-10px;top:50%;margin-top:-10px;}
.i_wall_bottom{position:absolute;left:50%;bottom:-16px;margin-left:-10px;}

.i_sink{position:absolute;left:20px;top:30px;width:100px;height:30px;padding-top: 10px;}
.i_stove{position:absolute;right:20px;top:30px;width:100px;height:30px;padding-top: 10px;}


.i_wall_left_obj_on{border-right: 2px solid red;}
.i_wall_top_obj_on{border-bottom: 2px solid red;}
.i_wall_right_obj_on{border-left: 2px solid red;}
.i_wall_bottom_obj_on{border-top: 2px solid red;}


#schema_L{width:70%;height: 200px;margin: 49px auto 0;position:relative;}
.l_wall_1_obj{position:absolute;width:10px;border-right: 2px solid #0078bf;height:200px;left:-10px;top:0;}
.l_wall_2_obj{position:absolute;width:100%;border-bottom: 2px solid #0078bf;height:10px;left:0;top:-10px;}
.l_wall_3_obj{position:absolute;width:10px;border-left: 2px solid #0078bf;height:100px;right:-10px;top:0;}
.l_wall_4_obj{position:absolute;width:70%;border-top: 2px solid #0078bf;height:10px;right:-0;top:100px;}
.l_wall_5_obj{position:absolute;width:10px;border-left: 2px solid #0078bf;height:100px;left:30%;top:100px;}
.l_wall_6_obj{position:absolute;width:30%;border-top: 2px solid #0078bf;height:10px;left:0;bottom:-10px;}

.l_wall_1_obj_on{border-right: 2px solid red;}
.l_wall_2_obj_on{border-bottom: 2px solid red;}
.l_wall_3_obj_on{border-left: 2px solid red;}
.l_wall_4_obj_on{border-top: 2px solid red;}
.l_wall_5_obj_on{border-left: 2px solid red;}
.l_wall_6_obj_on{border-top: 2px solid red;}

.l_wall_1{position:absolute;left:-10px;top:50%;margin-top:-10px;}
.l_wall_2{position:absolute;left:50%;top:-10px;margin-left:-10px;}
.l_wall_3{position:absolute;right:-10px;top:25%;margin-top:-13px;}
.l_wall_4{position:absolute;left:65%;top:50%;margin-top:-11px;margin-left:-10px;}
.l_wall_5{position:absolute;left:30%;bottom:25%;margin-bottom: -10px;margin-left: -7px;}
.l_wall_6{bottom: -16px;left: 15%;margin-left: -10px;position: absolute;}




.l_corner_1_obj_on{background-position: 0 -109px;}
.l_corner_2_obj_on{background-position: -55px -110px;}
.l_corner_3_obj_on{background-position: right bottom;}
.l_corner_4_obj_on{background-position: 0 -109px;}
.l_corner_5_obj_on{background-position: right bottom;}
.l_corner_6_obj_on{background-position: left bottom;}



.l_length_1{left:-140px;top:50%;}
.l_length_2{top:-50px;left:50%;}
.l_length_3{right:-121px;top:15%;}
.l_length_4{top:50%;margin-top: 15px;right:15%;}
.l_length_5{left:30%;bottom:25%;margin-bottom: -49px;margin-left: 23px;}
.l_length_6{bottom:-59px;left:15%;}


.l_sink{position:absolute;left:6%;top:10%;width:30%;height:25%;padding-top: 4%;}
.l_stove{position:absolute;right:6%;top:10%;width:30%;height:25%;padding-top: 4%;}



#schema_U{width:70%;height: 200px;margin: 49px auto 0;position:relative;}
.u_wall_1_obj{position:absolute;width:10px;border-right: 2px solid #0078bf;height:200px;left:-10px;top:0;}
.u_wall_2_obj{position:absolute;width:100%;border-bottom: 2px solid #0078bf;height:10px;left:0;top:-10px;}
.u_wall_3_obj{position:absolute;width:10px;border-left: 2px solid #0078bf;height:200px;right:-10px;top:0;}
.u_wall_4_obj{position:absolute;width:30%;border-top: 2px solid #0078bf;height:10px;right:-0;top:200px;}
.u_wall_5_obj{position:absolute;width:10px;border-right: 2px solid #0078bf;height:100px;right:30%;top:100px;}
.u_wall_6_obj{position:absolute;width:40%;border-top: 2px solid #0078bf;height:10px;left:30%;top:100px;}
.u_wall_7_obj{position:absolute;width:10px;border-left: 2px solid #0078bf;height:100px;left:30%;top:100px;}
.u_wall_8_obj{position:absolute;width:30%;border-top: 2px solid #0078bf;height:10px;left:0;top:200px;}



.u_wall_1_obj_on{border-right: 2px solid red;}
.u_wall_2_obj_on{border-bottom: 2px solid red;}
.u_wall_3_obj_on{border-left: 2px solid red;}
.u_wall_4_obj_on{border-top: 2px solid red;}
.u_wall_5_obj_on{border-right: 2px solid red;}
.u_wall_6_obj_on{border-bottom: 2px solid red;}
.u_wall_7_obj_on{border-left: 2px solid red;}
.u_wall_8_obj_on{border-top: 2px solid red;}

.u_wall_1{position:absolute;left:-10px;top:50%;margin-top:-10px;}
.u_wall_2{position:absolute;left:50%;top:-10px;margin-left:-10px;}
.u_wall_3{position:absolute;right:-10px;top:50%;margin-top:-13px;}
.u_wall_4{position:absolute;right:15%;bottom:-16px;margin-right:-10px;}
.u_wall_5{position:absolute;right:30%;bottom:25%;margin-right:-7px;}
.u_wall_6{position:absolute;left:50%;top:50%;margin-top:-13px;margin-left:-10px;}
.u_wall_7{position:absolute;left:30%;bottom:25%;margin-left:-7px;}
.u_wall_8{position:absolute;left:15%;bottom:-16px;margin-right:-10px;}



.u_corner_1_obj_on{position:absolute;width:30px;height:28px;top:-4px;left:-4px;background-color:#fff;overflow: hidden;border:1px solid red;}
.u_corner_1_obj_on .pdf{position:absolute;top:4px;left:4px;width:40px;height:34px;border-left: 2px solid #0078bf;border-top: 2px solid #0078bf;border-radius: 10px;}
.u_corner_2_obj_on{position:absolute;width:30px;height:28px;top:-4px;right:-4px;background-color:#fff;overflow: hidden;border:1px solid red;}
.u_corner_2_obj_on .pdf{position:absolute;top:4px;right:4px;width:40px;height:34px;border-right: 2px solid #0078bf;border-top: 2px solid #0078bf;border-radius: 10px;}
.u_corner_3_obj_on{position:absolute;width:30px;height:28px;top:204px;right:-4px;background-color:#fff;overflow: hidden;}
.u_corner_4_obj_on{position:absolute;width:30px;height:28px;top:204px;right:30%;margin-left:-4px;background-color:#fff;overflow: hidden;}
.u_corner_5_obj_on{position:absolute;width:30px;height:28px;top:-104px;right:30%;background-color:#fff;overflow: hidden;}
.u_corner_6_obj_on{position:absolute;width:30px;height:28px;top:-104px;left:30%;background-color:#fff;overflow: hidden;}
.u_corner_7_obj_on{position:absolute;width:30px;height:28px;top:-204px;left:30%;background-color:#fff;overflow: hidden;}
.u_corner_8_obj_on{position:absolute;width:30px;height:28px;top:-204px;left:-4px;background-color:#fff;overflow: hidden;}



.u_sink{position:absolute;left:6%;top:10%;width:30%;height:25%;padding-top: 4%;}
.u_stove{position:absolute;right:6%;top:10%;width:30%;height:25%;padding-top: 4%;}


.u_length_1{left:0;top:100px;}
.u_length_2{top:-10px;left:100px;}
.u_length_3{right:0;top:50px;}
.u_length_4{bottom:-10px;right:15%;}
.u_length_5{right:50%;top:25%50px;}
.u_length_6{top:100px;left:50%;margin-top: 17px;margin-left: -50px;}
.u_length_7{left:30%;bottom:10px;margin-bottom: -28px;margin-left: 12px;}
.u_length_8{bottom:-10px;left:15%;}

.blueprint{width:80%;margin: 0 auto;position:relative;margin-top:50px;height:260px !important;overflow: hidden;}
.wall{display:none;}
.calc_table_container{font-size: 0.8em;}
 </style>

  <body>
      <h1>My Name is Blah ываыва ыва ыва ыва ыва ыва ыва укеепрр оболдю asdasda фывфывфыв</h1>
     

      <div class="blueprint">
                     
                     <?php echo $this->blueprint; ?>
      </div><!--  blueprint  -->
      <?php echo $this->order_table; ?>



  </body>
</html> 