<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<style>
  body { font-family: DejaVu Sans, sans-serif; }
 </style>
  <body>
      <h1> !!!Это такое другое письмо My Name is Blah ываыва ыва ыва ыва ыва ыва ыва укеепрр оболдю asdasda фывфывфыв</h1>
      <div style="position:absolute; top:200px;left:20px;border:3px solid red;width:400px;height:100px"></div>
      <div style="position:absolute; top:220px;left:20px;border:3px solid red;width:400px;height:100px;background:yellow"></div>
      <table class="table table-hover calc_table" cellpadding="0" cellspacing="0" width="100%">
                              <thead>
                                    <tr><th>Наименование</th><th>Размер/количество</th><th>Цена</th><th>Стоимость</th></tr>

                              </thead>
                              <tbody>
                                
                                    <tr><td>материал</td><td><div id="result_sq">1.320 кв.м</div></td><td></td><td></td></tr>
                                    <tr><td>Длина обработки края</td><td><div id="result_edge_len">6000 мм</div></td><td><span id="price_edge"></span></td><td></td></tr>
                                    <tr><td>Длина плинтуса</td><td><div id="result_plinth_len">0 мм</div></td><td></td><td></td></tr>
                                    <tr><td>Скругления углов</td><td><div id="result_corner">0 шт.</div></td><td></td><td></td></tr>
                                    <tr><td>Мойка</td><td><div id="result_sink">нет</div></td><td></td><td></td></tr>
                                    <tr><td>Плита</td><td><div id="result_stove">нет</div></td><td></td><td></td></tr>
                              </tbody>
                              <tfoot><tr><td colspan="3">Итого:</td><td></td></tr></tfoot>
                            </table>

  </body>
</html> 