<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'phpDocumentor' => array($vendorDir . '/phpdocumentor/reflection-docblock/src'),
    'ZfcUser' => array($vendorDir . '/zf-commons/zfc-user/src'),
    'ZfcTwig\\' => array($vendorDir . '/zf-commons/zfc-twig/src'),
    'ZfcBase' => array($vendorDir . '/zf-commons/zfc-base/src'),
    'ZfcAdmin' => array($vendorDir . '/zf-commons/zfc-admin/src'),
    'ZendXml\\' => array($vendorDir . '/zendframework/zendxml/library'),
    'ZendDeveloperTools' => array($vendorDir . '/zendframework/zend-developer-tools/src'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'BjyProfiler' => array($vendorDir . '/bjyoungblood/bjy-profiler/src'),
    'BjyAuthorize\\' => array($vendorDir . '/bjyoungblood/bjy-authorize/src'),
);
